---
title: "Hello, Tiny Data World"
description: "Kicking off this blog with a fruity dataset."
date: 2025-11-22
categories: [intro, meta]
format:
  html:
    toc: false
    code-fold: false
---

This is my very first tiny data story.

It's the weekend, end of 1st week of Block 3 at UBC MDS. All my assignments that were due at 6pm have been submitted. There is a small window of a break before we get to Monday and it all starts over. Anyway, I've been meaning to start a tiny blog (micro blog?) like this for a while, but never got to it, so now I'm finally here. You're reading this because I finally found some time to put it all together.

The whole point of this tiny blog is to get me to practice looking at small bits and pieces of data regularly. Every now and then I come across some interesting small datasets, or I personally have some interesting small datasets from my own life that I'm interested in, and I want to try to use code and data analysis to answer some questions. So ya, that's the point of this... micro blog. Let's call it that for now.

Right now, the goal is just to make sure everything works: the blog, the code, and the render. Everything should me more or less: load data, do analysis, add commentary, push blog post, and let quarto publish automatically. I don't want to deal with the details of managing a blog site, so that's why I'm letting quarto and github power all of this.

Well, let's start with our very first tiny data set just to make sure things are running as expected. Here I'm going to use python pandas and just create a small table of some of my favourite fruits. That is all, stay tuned for more!

```{python}
import pandas as pd

df = pd.DataFrame({
    "fruit": ["apple", "banana", "kiwi", "guava", "mango", "pear"],
    "rating": [8, 6, 8, 9, 8, 7]
})
df
```
